#!/bin/bash

OPENSHIFT_RHCOS_MAJOR_REL="4.2"
OPENSHIFT_RHCOS_MINOR_REL=""

if [[ $OPENSHIFT_RHCOS_MAJOR_REL == "" || $OPENSHIFT_RHCOS_MAJOR_REL == "latest" || ($OPENSHIFT_RHCOS_MAJOR_REL != "4.1" && $OPENSHIFT_RHCOS_MAJOR_REL != "4.2") ]]; then
    OPENSHIFT_RHCOS_MAJOR_REL="4.3"
    OPENSHIFT_RHCOS_MINOR_REL=""
fi

export OPENSHIFT_RHCOS_MAJOR_REL
export OPENSHIFT_RHCOS_MINOR_REL

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PROJECT_DIR

PATCH_NM_WAIT=true
export PATCH_NM_WAIT