apiVersion: metalkube.org/v1alpha1

kind: BareMetalHost
metadata:
  name: master-2
  annotations:
      kni.io/sdnNetworkMac: "0c:c4:7a:19:6f:7e"
#     kni.io/sdnIPv4: "192.168.111.13"

spec:
  externallyProvisioned: true
  online: true
  hardwareProfile: "master"
  bmc:
    address: ipmi://10.19.110.8
    credentialsName: ha-lab-ipmi
  bootMACAddress: 0C:C4:7A:DB:AC:03

  